<?php namespace ProcessWire;

/**
 * ProcessWire Thinspace Plus Module
 *
 * “Flatten” a text by replacing newline characters (as well as repeated
 * consecutive whitespace characters) with just one space character.
 * Extends Netcarver’s original Thinspace module.
 *
 * @author    Netcarver
 * @author    Michael van Laar <michael@van-laar.de>
 * @copyright Copyright of original Thinspace module (c) 2012, Netcarver (https://github.com/netcarver)
 *
 * This file is licensed under the MIT license
 * https://processwire.com/about/license/mit/
 *
 * ProcessWire 3.x, Copyright 2015 by Ryan Cramer
 * http://www.processwire.com
 *
 */

class TextformatterThinspacePlus extends Textformatter implements Module {

    public static function getModuleInfo() {
        return array(
            'title'     => __('Thinspace Plus'),
            'version'   => '1.0.3',
            'summary'   => __("“Flatten” a text by replacing newline characters (as well as repeated consecutive whitespace characters) with just one space character. Extends Netcarver’s original Thinspace module."),
            'author'    => 'Michael van Laar',
            'href'      => 'https://github.com/MichaelvanLaar/PW-TextformatterThinspacePlus',
            'requires'  => 'ProcessWire>=3.0.0',
        );
    }



    /**
     * Format the input string
     *
     * @param string $str The block of text to parse
     *
     * The incoming string is replaced with the formatted version of itself.
     **/
    public function format(&$str) {
        $str = trim(preg_replace('/\s+/', ' ', $str));
    }
}
